2024-03-19 12:38:54,894 - web - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: users.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/web/accounts/views.py", line 16, in register
    if form.validate_on_submit():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/flask_wtf/form.py", line 86, in validate_on_submit
    return self.is_submitted() and self.validate(extra_validators=extra_validators)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/web/accounts/forms.py", line 22, in validate
    user = User.query.filter_by(username=self.username.data).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2191, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1421, in execute
    return meth(
           ^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1643, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1849, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1989, in _exec_single_context
    self._handle_dbapi_exception(
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1970, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/colesnipes/Documents/GitHub/swen320_2024S_password_manager_EllerSnipes-1/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: users.username
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users.token AS users_token, users."encryptedPass" AS "users_encryptedPass", users."key" AS users_key 
FROM users 
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('cole.snipe', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
